

services:
  backend:
    build: ./backend
    container_name: ai-backend
    restart: always
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: ai-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

